name: healmeal_app
description: "Bangladesh's trusted online pharmacy & healthcare platform"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^13.2.0
  flutter_bloc: ^8.1.5
  get_it: ^9.2.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.2
  pinput: ^5.0.0
  badges: ^3.2.0
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.1.0
  dotted_border: ^2.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  share_plus: ^13.1.0
  google_fonts: ^6.2.1
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  firebase_messaging: ^16.4.0
  image_picker: ^1.2.2
  collection: ^1.19.1
  http: ^1.6.0
  speech_to_text: ^7.4.0
  flutter_dotenv: ^6.0.1
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^22.0.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^9.1.0          # Cubit/Bloc unit testing
  mocktail: ^0.3.0          # Simple mocking library
  integration_test:
    sdk: flutter           # E2E on real APK

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/data.json

  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansBengali-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansBengali-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/healmeal_logo.webp"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/healmeal_logo.webp"
  android_12:
    image: "assets/images/healmeal_logo.webp"
    color: "#ffffff"
