List<String> districts = <String>[
  'Bagerhat',
  'Bandarban',
  'Barguna',
  'Barishal',
  'Bhola',
  'Bogura',
  'Brahmanbaria',
  'Chandpur',
  'Chattogram',
  'Cumilla',
  'Dhaka',
  'Dinajpur',
  'Faridpur',
  'Gazipur',
  'Gopalganj',
  'Jamalpur',
  'Jashore',
  'Khulna',
  'Kishoreganj',
  'Kurigram',
  'Madaripur',
  'Manikganj',
  'Moulvibazar',
  'Munshiganj',
  'Mymensingh',
  'Naogaon',
  'Narayanganj',
  'Narsingdi',
  'Noakhali',
  'Pabna',
  'Rajshahi',
  'Rangpur',
  'Satkhira',
  'Shariatpur',
  'Sherpur',
  'Sirajganj',
  'Sylhet',
  'Tangail',
];

Map<String, List<String>> upazilasByDistrict = <String, List<String>>{
  'Dhaka': <String>['Dhanmondi', 'Tejgaon', 'Mirpur', 'Uttara', 'Mohammadpur'],
  'Gazipur': <String>['Tongi', 'Sreepur', 'Kaliakair', 'Gazipur Sadar'],
  'Chattogram': <String>['Pahartali', 'Panchlaish', 'Kotwali', 'Halishahar'],
  'Cumilla': <String>['Cumilla Sadar', 'Daudkandi', 'Laksam', 'Burichang'],
  'Rajshahi': <String>['Boalia', 'Motihar', 'Paba', 'Godagari'],
  'Khulna': <String>['Khalishpur', 'Sonadanga', 'Dumuria', 'Rupsha'],
};
